// <auto-generated />
namespace Intercambealo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Files : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Files));
        
        string IMigrationMetadata.Id
        {
            get { return "201507131624563_Files"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
